FROM node:12-alpine

WORKDIR /usr/src/app/app-ui

COPY package*.json ./

RUN npm install -g @angular/cli @angular-devkit/build-angular --unsafe-perm=true && npm install

EXPOSE 4200

CMD ["npm", "start"]